DROP TABLE IF EXISTS imbibe_posts;
CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');

CREATE TABLE imbibe_posts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    idDrink TEXT NOT NULL,
    strDrink TEXT NOT NULL,
    strTags TEXT,
    strCategory TEXT,
    strIBA TEXT,
    strGlass TEXT NOT NULL,
    strInstructions TEXT NOT NULL,
    strDrinkThumb TEXT ,
    strIngredient1 TEXT NOT NULL,
    strIngredient2 TEXT,
    strIngredient3 TEXT,
    strIngredient4 TEXT,
    strIngredient5 TEXT,
    strIngredient6 TEXT,
    strIngredient7 TEXT,
    strMeasure1 TEXT NOT NULL,
    strMeasure2 TEXT,
    strMeasure3 TEXT,
    strMeasure4 TEXT,
    strMeasure5 TEXT,
    strMeasure6 TEXT,
    strMeasure7 TEXT,
    userNotes TEXT,
    rating star_rating,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    user_id INTEGER REFERENCES imbibe_users(id) ON DELETE CASCADE NOT NULL
);